In [56]:
import numpy as np
names=np.array(['王微','肖良英','方绮雯','刘旭阳','钱易铭'])
subjects=np.array(['Math','English','Python','Chinese','Art','Database','Physics'])

In [57]:
scores=np.array([[70,85,77,90,82,84,89],
                 [60,64,80,75,80,92,90],
                 [90,93,88,87,86,90,91],
                 [80,82,91,88,83,86,80],
                 [88,72,78,90,91,73,80]])

In [58]:
scores+5

array([[75, 90, 82, 95, 87, 89, 94],
       [65, 69, 85, 80, 85, 97, 95],
       [95, 98, 93, 92, 91, 95, 96],
       [85, 87, 96, 93, 88, 91, 85],
       [93, 77, 83, 95, 96, 78, 85]])

In [59]:
a=np.ones((5,7))*5
print(a)

[[5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5.]]


In [60]:
scores+a

array([[75., 90., 82., 95., 87., 89., 94.],
       [65., 69., 85., 80., 85., 97., 95.],
       [95., 98., 93., 92., 91., 95., 96.],
       [85., 87., 96., 93., 88., 91., 85.],
       [93., 77., 83., 95., 96., 78., 85.]])

In [61]:
bonus=np.array([3,4,5,3,6,7,2])
scores+bonus

array([[73, 89, 82, 93, 88, 91, 91],
       [63, 68, 85, 78, 86, 99, 92],
       [93, 97, 93, 90, 92, 97, 93],
       [83, 86, 96, 91, 89, 93, 82],
       [91, 76, 83, 93, 97, 80, 82]])

In [62]:
scores[names=='肖良英',subjects=='English']

array([64])

In [63]:
scores[names=='肖良英',subjects=='English']+5

array([69])

In [64]:
np.floor(scores/10)

array([[7., 8., 7., 9., 8., 8., 8.],
       [6., 6., 8., 7., 8., 9., 9.],
       [9., 9., 8., 8., 8., 9., 9.],
       [8., 8., 9., 8., 8., 8., 8.],
       [8., 7., 7., 9., 9., 7., 8.]])

In [65]:
np.subtract(scores,3)

array([[67, 82, 74, 87, 79, 81, 86],
       [57, 61, 77, 72, 77, 89, 87],
       [87, 90, 85, 84, 83, 87, 88],
       [77, 79, 88, 85, 80, 83, 77],
       [85, 69, 75, 87, 88, 70, 77]])

In [66]:
scores.sum(axis=0)

array([388, 396, 414, 430, 422, 425, 430])

In [67]:
scores[names=='王微'].mean()

82.42857142857143

In [68]:
names[scores[:,subjects=='English'].argmax()]

'方绮雯'

In [69]:
np.random.randint(0,6,10)

array([3, 0, 5, 2, 2, 4, 2, 1, 1, 2])

In [70]:
np.random.randint(0,2,size=(5,6))

array([[1, 0, 1, 0, 0, 1],
       [1, 1, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0]])

In [71]:
np.random.normal(0,1,size=(4,5))

array([[ 0.29253536,  0.60582487, -0.73219688, -1.67641957, -1.54004788],
       [ 1.0241463 ,  0.19370467,  3.31525645,  1.29382428, -0.53954864],
       [-0.71616284,  1.31170925,  0.82208053,  0.84847714, -0.65597277],
       [ 1.00228412,  1.1705506 , -1.23457733,  1.4593541 , -0.64012008]])