In [38]:
import numpy as np
names=np.array(['王微','肖良英','方绮雯','刘旭阳','钱易铭'])
subjects=np.array(['Math','English','Python','Chinese','Art','Database','Physics'])

In [5]:
names.ndim

1

In [6]:
names.size

5

In [7]:
names.dtype

dtype('<U3')

In [9]:
names[2]

'方绮雯'

In [10]:
subjects[-3]

'Art'

In [11]:
subjects[[0,2,4]]

array(['Math', 'Python', 'Art'], dtype='<U8')

In [12]:
names[1:4]

array(['肖良英', '方绮雯', '刘旭阳'], dtype='<U3')

In [13]:
subjects[0:-1:2]

array(['Math', 'Python', 'Art'], dtype='<U8')

In [15]:
mask=(names=='王微')|(names=='钱易铭')
names[mask]

array(['王微', '钱易铭'], dtype='<U3')

In [16]:
scores=np.array([[70,85,77,90,82,84,89],[60,64,80,75,80,92,90],[90,93,88,87,86,90,91],[80,82,91,88,83,86,80],[88,72,78,90,91,73,80]])

In [17]:
scores.ndim

2

In [18]:
scores.size

35

In [19]:
scores.shape

(5, 7)

In [20]:
scores.dtype

dtype('int32')

In [21]:
scores[1,0]

60

In [22]:
scores[[1,3],[0,1]]

array([60, 82])

In [23]:
scores[[1,3]]

array([[60, 64, 80, 75, 80, 92, 90],
       [80, 82, 91, 88, 83, 86, 80]])

In [24]:
scores[:,[0,1]]

array([[70, 85],
       [60, 64],
       [90, 93],
       [80, 82],
       [88, 72]])

In [25]:
scores[[0,3],1:4]

array([[85, 77, 90],
       [82, 91, 88]])

In [29]:
scores[[1,3]][:,[0,1]]

array([[60, 64],
       [80, 82]])

In [30]:
scores[(names=='肖良英')|(names=='方绮雯'),:]

array([[60, 64, 80, 75, 80, 92, 90],
       [90, 93, 88, 87, 86, 90, 91]])

In [31]:
scores[(names=='肖良英')|(names=='方绮雯')][:,(subjects=='Math')|(subjects=='Python')]

array([[60, 80],
       [90, 88]])

In [32]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.arange(3,11,2)

array([3, 5, 7, 9])

In [34]:
np.arange(0.3,1.5,0.3)

array([0.3, 0.6, 0.9, 1.2])

In [35]:
np.arange(0,15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])