###   创建一维数组

In [2]:
import numpy as np
names=np.array(['王薇','肖良英','方绮雯','刘旭阳','钱易铭'])
subjects=np.array(['Math','English','Python','Chinese','Art','Database','Physics'])


###  创建二维数组 scores

In [3]:
scores=np.array([[70,85,77,90,82,84,89],
                 [60,64,80,75,80,92,90],
                 [90,93,88,87,86,90,91],
                 [80,82,91,88,83,86,80],
                 [88,72,78,90,91,73,80]])

In [4]:
scores

array([[70, 85, 77, 90, 82, 84, 89],
       [60, 64, 80, 75, 80, 92, 90],
       [90, 93, 88, 87, 86, 90, 91],
       [80, 82, 91, 88, 83, 86, 80],
       [88, 72, 78, 90, 91, 73, 80]])

### 1. 选取scores中第2行第2列元素

In [5]:
scores[1,1]

64

### 2.选取scores中两个元素，行序号为0，列序号为1的元素；
###    以及行序号为3，列序号为6的元素。

In [6]:
scores[[0,3],[1,6]]

array([85, 80])

### 3. 选取数组scores中的前3行数据

In [10]:
scores[0:3]

array([[70, 85, 77, 90, 82, 84, 89],
       [60, 64, 80, 75, 80, 92, 90],
       [90, 93, 88, 87, 86, 90, 91]])

### 4. 选取scores中，列序号为1--4 的列

In [13]:
scores[:,1:5]

array([[85, 77, 90, 82],
       [64, 80, 75, 80],
       [93, 88, 87, 86],
       [82, 91, 88, 83],
       [72, 78, 90, 91]])

### 5. 选取scores中，行序号为1,2，列序号为0,2,4 的元素

In [7]:
scores[1:3,0:5:2]

array([[60, 80, 80],
       [90, 88, 86]])

### 6. 选取钱易铭的成绩

In [8]:
scores[(names=='钱易铭')]

array([[88, 72, 78, 90, 91, 73, 80]])

### 7. 选取钱易铭的数学成绩

In [9]:
scores[(names=='钱易铭')][:,(subjects=='Math')]

array([[88]])

### 8.选取王薇和肖良英的数学和英语成绩

In [10]:
scores[(names=='王薇')|(names=='肖良英')][:,(subjects=='Math')|(subjects=='English')]

array([[70, 85],
       [60, 64]])

### 9. 选取scores中，大于等于80并且小于90的元素

In [14]:
scores[(scores>=80)&(scores<=90)]

array([85, 90, 82, 84, 89, 80, 80, 90, 90, 88, 87, 86, 90, 80, 82, 88, 83,
       86, 80, 88, 90, 80])

###  10. 将第1列元素的值都增加5

In [22]:
scores[:,0]+5

array([75, 65, 95, 85, 93])